name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "true"
    - name: Install llvm
      run: sudo apt update && sudo apt install -y clang llvm clang-format
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Clone deps
      run: |
        git clone https://github.com/nervosnetwork/ckb-c-stdlib ci_deps/ckb-c-stdlib
        cd ci_deps/ckb-c-stdlib
        git checkout 7245b6268ef623f204501dc2beb6b3ae7d7b3cf4
    - name: make
      run: make CKB_C_STDLIB=ci_deps/ckb-c-stdlib
    - name: git diff
      run: git diff --exit-code

  macos-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install latest llvm
      run: brew install llvm
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Clone deps
      run: |
        git clone https://github.com/nervosnetwork/ckb-c-stdlib ci_deps/ckb-c-stdlib
        cd ci_deps/ckb-c-stdlib
        git checkout 7245b6268ef623f204501dc2beb6b3ae7d7b3cf4
    - name: make
      run: make CKB_C_STDLIB=ci_deps/ckb-c-stdlib
    - name: git diff
      run: git diff --exit-code
