name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "true"
    - name: Install deps
      run: sudo apt update && sudo apt install -y clang llvm clang-format protobuf-compiler pkg-config
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Clone deps
      run: |
        git clone https://github.com/nervosnetwork/ckb-c-stdlib ci_deps/ckb-c-stdlib
        cd ci_deps/ckb-c-stdlib
        git checkout 7245b6268ef623f204501dc2beb6b3ae7d7b3cf4
        cd ../..
        git clone https://github.com/google/libprotobuf-mutator ci_deps/libprotobuf-mutator
        cd ci_deps/libprotobuf-mutator
        git checkout dc4ced337a9fb4047e2dc727268fbac55ca82f73
    - name: make
      run: |
        make CKB_C_STDLIB=ci_deps/ckb-c-stdlib LIBPROTOBUF_MUTATOR=ci_deps/libprotobuf-mutator \
          gen-proto fmt flatten test-build
    - name: git diff
      run: git diff --exit-code

  macos-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install deps
      run: brew install llvm protobuf@3 pkgconfig
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Clone deps
      run: |
        git clone https://github.com/nervosnetwork/ckb-c-stdlib ci_deps/ckb-c-stdlib
        cd ci_deps/ckb-c-stdlib
        git checkout 7245b6268ef623f204501dc2beb6b3ae7d7b3cf4
        cd ../..
        git clone https://github.com/google/libprotobuf-mutator ci_deps/libprotobuf-mutator
        cd ci_deps/libprotobuf-mutator
        git checkout dc4ced337a9fb4047e2dc727268fbac55ca82f73
    - name: make
      run: |
        export PKG_CONFIG_PATH="/usr/local/opt/protobuf@3/lib/pkgconfig"
        make \
          PROTOC=/usr/local/opt/protobuf@3/bin/protoc
          CKB_C_STDLIB=ci_deps/ckb-c-stdlib \
          LIBPROTOBUF_MUTATOR=ci_deps/libprotobuf-mutator \
          gen-proto fmt flatten test-build
    - name: git diff
      run: git diff --exit-code
