[package]
name = "fdp-ckb-syscalls"
version = "0.1.0"
edition = "2024"

[dependencies]
ckb-c-to-std-syscalls = { path = "../ckb-c-to-std-syscalls" }
ckb-syscall-defs = { path = "../syscall-defs", features = ["ckb-std"] }
ckb-std.workspace = true

[build-dependencies]
cc = "1.0"
