[package]
name = "fdp-ckb-syscalls"
version = "0.1.0"
edition = "2024"

[dependencies]
ckb-vm-fuzzing-utils = { path = "../ckb-vm-fuzzing-utils" }
ckb-std.workspace = true

[build-dependencies]
cc = "1.0"

[features]
default = ["std"]
std = []
